# To switch db to TimescaleDB, change TIMESCALEDB=true, SPRING_PROFILES_ACTIVE=v2 and change db image
version: "3.7"
services:
  rosetta:
    image: gcr.io/mirrornode/hedera-mirror-rosetta:0.45.0
    pull_policy: always
    restart: unless-stopped
    tty: true
    volumes:
      - ./application.yml:/src/hedera-mirror-rosetta/application.yml
    ports:
      - 5700:5700
